const malla = [
  { nombre: "Introducción a la Clínica Médica I" },
  { nombre: "Autorregulación para el Profesionalismo y Práctica de la Medicina" },
  { nombre: "Salud y Sociedad I" },
  { nombre: "Organismo Humano I" },
  { nombre: "Estructura y Función Celular I" },
  { nombre: "Lengua Materna" },
  { nombre: "Asignatura Electiva 1" },
  { nombre: "Introducción a la Clínica Médica II", requisitos: ["Introducción a la Clínica Médica I"] },
  { nombre: "Salud y Sociedad II", requisitos: ["Salud y Sociedad I"] },
  { nombre: "Organismo Humano II", requisitos: ["Organismo Humano I"] },
  { nombre: "Patógenos y Defensa" },
  { nombre: "Profesionalismo y Práctica de la Medicina" },
  { nombre: "Asignatura Electiva 2" },
  { nombre: "Metodología de la Investigación" },
  { nombre: "Integrado: Introducción a la Semiología" },
  { nombre: "Integrado: Sistema Hematología" },
  { nombre: "Integrado: Aparato Locomotor" },
  { nombre: "Integrado: Endocrinología y Diabetes" },
  { nombre: "Integrado: Reproducción Humana" },
  { nombre: "Integrado: Dermatología" },
  { nombre: "Integrado: Introducción a la Cirugía" },
  { nombre: "Inglés" },
  { nombre: "Asignatura Electiva 3" },
  { nombre: "Medicina Basada en la Evidencia" },
  { nombre: "Integrado: Enfermedades Respiratorias" },
  { nombre: "Integrado: Enfermedades Cardiovasculares" },
  { nombre: "Integrado: Enfermedades Neurológicas" },
  { nombre: "Integrado: Enfermedades Nefrourológicas" },
  { nombre: "Integrado: Enfermedades Otorrinolaringológicas" },
  { nombre: "Integrado: Enfermedades Oftalmológicas" },
  { nombre: "Integrado: Enfermedades del Aparato Digestivo" },
  { nombre: "TIPE: Clínica Salud Familiar" },
  { nombre: "Clínica de la Mujer" },
  { nombre: "Clínica del Niño y del Adol

